FROM docker.elastic.co/beats/filebeat:8.13.0

# Copia la configurazione
COPY filebeat-suricata.yml /usr/share/filebeat/filebeat.yml

# Imposta i permessi corretti (solo owner può scrivere)
USER root
RUN chmod 600 /usr/share/filebeat/filebeat.yml && \
    chown root:root /usr/share/filebeat/filebeat.yml

USER filebeat

